productName = "PC Remote"
version = "0.1.1"
identifier = "com.fuderis.pc-remote"

[build]
frontendDist = "ui"

[app]
withGlobalTauri = true

[[app.windows]]
url = "views/main.html"
title = "PC Remote"
width = 1000
height = 650
resizable = true
fullscreen = false
visible = false

[app.security]
csp = ""

[bundle]
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
resources = [
  "bin",
  "icon.ico"
]
